Make isAvailable a regular fun
jordond/compass pull request #105
Opened 2024-08-27 23:42 UTC by cristan

Solves https://github.com/jordond/compass/issues/101

2024-08-28 19:19 UTC, jordond requested changes
You must run `./gradlew apiDump` when a change to the public API is made. See [here](https://compass.jordond.dev/docs/misc/contributing)

2024-08-30 10:01 UTC, cristan commented
I ran the command now :)

2024-10-03 15:34 UTC, jordond approved these changes
As this is a breaking chang, they will have to wait for a major release 👍

2024-12-19 20:07 UTC, jordond approved these changes

2024-12-19 20:08 UTC, merged